### ISSUE TITLE
Not working; fix path

### ISSUE THREAD

**Issue by hasecilu** [Aki78/blender_latex#1]
Hello, I'm using Ubuntu 20.04, have installed texlive-full and followed the instructions. The add-on was installed correctly but when I tried to use it it did not work (Blender 2.82 & Blender 2.92). 

**Short story**: Fix the path, line 48 and forward.

**Long boring story**:

[I tried to insert the command \\\\Psi but in the terminal the next errors showed:]

\\\\Psi
cp: cannot stat '/home/aki/.latex_blender/latex_blender_template.tex': No such file or directory
sed: can't read /home/aki/.latex_blender/template2.tex: No such file or directory
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
! I can't find file `/home/aki/.latex_blender/template2.tex'.
<*> /home/aki/.latex_blender/template2.tex
                                          
I suspect the error is due to in the code the path is not updated according to the user (/home/aki/.latex_blender/template2.tex) so I changed the path using my name and it worked.

Nice job. Working in Blender 2.82 & Blender 2.92.

**Comment by Aki78** [comment]
Thank you!
